# This is a basic workflow to help you get started with Actions

name: Hello Actions

# Controls when the workflow will run
on:
  push:
    branches: 
    - master

  pull_request:
    types: [closed]
  
  workflow_dispatch:
env:
  name: arechste
jobs:
  build:
    
    runs-on: ubuntu-latest
    env:
      name: Alex R.
    steps:
    - name: Run a one-line script
      run: | 
        echo Hello $name!
        echo Actor: ${{ github.actor }}
        echo Committed By: ${{ github.event.commits[0].author.name }}
      
  dump:
  
    runs-on: ubuntu-latest
    steps:
     - env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
       run: echo "$GITHUB_CONTEXT"
  
  weather:
    runs-on: ubuntu-latest
    env:
      location: '28.550, -81.40'
      lang: en
      units: us
      exclude: 'minutely,hourly,daily,alerts,flags'
      dark_sky_secret: ${{ secrets.dark_sky }}
    steps:
      - name: current weather
        run: curl -s --url https://api.darksky.net/forecast/$dark_sky_secret/$location?lang=$lang&units=$units&exclude=$exclude
      
  pull_request_only:
  
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: build
    steps:
    - name: Run a multi-line script
      run: |
         echo Add other actions to build,
         echo Hi , $name.
    
