# This is a basic workflow to help you get started with Actions

name: Hello Actions

# Controls when the workflow will run
on:
  push:
    branches: 
    - master

  pull_request:
    types: [closed]
  
  workflow_dispatch:
env:
  name: arechste
jobs:
  build:
    
    runs-on: ubuntu-latest
    name: Build Project
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with: | 
        node-version: '12.x'
    - name: install
      run: npm install
    - name: build
      run: npm run build 
    - name: deploy
      uses: demurgos/ga-deploy-git@v1
      with:
        accessToken: ${{ secrets.access_token }}
        srcDir: build
        destBranch: gh-pages
      
  dump:
  
    runs-on: ubuntu-latest
    steps:
     - env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
       run: echo "$GITHUB_CONTEXT"
  
  weather:
    runs-on: ubuntu-latest
    env:
      location: '28.550,-81.40'
      lang: en
      units: us
      exclude: 'minutely,hourly,daily,alerts,flags'
      dark_sky_secret: ${{ secrets.dark_sky }}
    steps:
      - name: current weather
        run: curl -s --url https://api.darksky.net/forecast/$dark_sky_secret/$location?lang=$lang&units=$units&exclude=$exclude
      
  pull_request_only:
  
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: build
    steps:
    - name: Run a multi-line script
      run: |
         echo Add other actions to build,
         echo Hi , $name.
    
